In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('os_ngd_buildings_s3_export_dsm_2025-08-26_091541.csv')

In [4]:
df.head(30)

,osid,uprnreference,region,buildinguse,description,versiondate,roofmaterial_capturemethod,roofmaterial_confidenceindicator,roofmaterial_evidencedate,roofmaterial_greenroofpresence,...,roofshapeaspect_areafacingwest_m2,roofshapeaspect_areaflat_m2,roofshapeaspect_areaindeterminable_m2,roofshapeaspect_areapitched_m2,roofshapeaspect_areatotal_m2,roofshapeaspect_capturemethod,roofshapeaspect_confidenceindicator,roofshapeaspect_evidencedate,roofshapeaspect_shape,roofshapeaspect_updatedate
0,00066497-1565-4713-babe-c447741fec49,"[{'uprn': 100100388269, 'buildingid': '0006649...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2024-05-19,Not Present,...,21.0,22.3,0.0,111.3,133.6,Automated Process,Expected Data Output,2024-05-19,Pitched,2025-03-10
1,00066680-6a52-45cb-a39b-d8304ca16554,"[{'uprn': 10093295670, 'buildingid': '00066680...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2022-07-11,Not Present,...,0.0,0.0,0.0,59.5,59.5,Automated Process,Expected Data Output,2022-07-11,Pitched,2025-03-10
2,00066cce-862b-4a8d-8832-b7ee8c71790e,"[{'uprn': 100100132862, 'buildingid': '00066cc...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,0.0,0.0,56.6,56.6,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
3,00066d41-8b44-49a8-b446-4dc09bda76a0,"[{'uprn': 100100096090, 'buildingid': '00066d4...",W92000004,Residential Accommodation,Multiple Residential Accommodation,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,0.0,0.0,4.8,67.5,72.3,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10
4,0006893a-d321-4836-b634-a3349e1fc893,"[{'uprn': 100100853617, 'buildingid': '0006893...",W92000004,Residential Accommodation,Semi-Detached House,2025-06-06,Automated Process,Expected Data Output,2022-06-16,Not Present,...,0.0,0.0,0.0,43.8,43.8,Automated Process,Expected Data Output,2022-06-16,Pitched,2025-05-30
5,00069e3f-4537-428e-ab58-a7783deb6486,"[{'uprn': 10094365947, 'buildingid': '00069e3f...",W92000004,Residential Accommodation,Semi-Detached House,2025-05-21,Default Value,New Building Surveyed After Imagery Capture,NaN,Unknown,...,NaN,NaN,NaN,NaN,NaN,Default Value,New Building Surveyed After Imagery Capture,NaN,Unknown,2025-04-12
6,0006a1fe-9610-4b55-b39e-05b33eb40495,"[{'uprn': 100100060644, 'buildingid': '0006a1f...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,44.0,0.0,4.8,89.4,94.2,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10
7,0006aaa2-48c1-4011-99ec-60e44670b303,"[{'uprn': 10009182606, 'buildingid': '0006aaa2...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,0.0,0.0,0.0,85.8,85.8,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10
8,0006b6aa-d809-47b8-990b-3fbf4b2de238,"[{'uprn': 100100030432, 'buildingid': '0006b6a...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,0.0,0.0,0.0,72.8,72.8,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10
9,0006cb7d-6315-462a-af8a-dc4bb4190ed5,"[{'uprn': 100100750607, 'buildingid': '0006cb7...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,8.0,0.0,0.0,49.8,49.8,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
10,0006db3a-be00-46ad-a397-0487bd3abd41,[],W92000004,Residential Accommodation,Residential Building,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,20.7,0.0,15.8,36.5,Automated Process,Expected Data Output,2023-05-20,Mixed,2025-03-10
11,0006fbc5-fbdb-4b5b-b327-dfd32e4ab2f9,"[{'uprn': 100100493577, 'buildingid': '0006fbc...",W92000004,Residential Accommodation,End-Of-Terrace House,2025-03-11,Automated Process,Expected Data Output,2024-05-19,Not Present,...,30.1,0.0,0.0,56.0,56.0,Automated Process,Expected Data Output,2024-05-19,Pitched,2025-03-10
12,00071edc-ac82-4470-9ed0-34cac49720c4,"[{'uprn': 100100331660, 'buildingid': '00071ed...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2024-05-19,Not Present,...,0.0,13.4,0.0,70.9,84.3,Automated Process,Expected Data Output,2024-05-19,Pitched,2025-03-10
13,00072190-8e01-4bf0-afe3-94526f90b597,"[{'uprn': 100100688784, 'buildingid': '0007219...",W92000004,Residential Accommodation,End-Of-Terrace House,2025-03-11,Automated Process,Expected Data Output,2022-07-11,Not Present,...,36.7,29.6,0.0,103.0,132.6,Automated Process,Expected Data Output,2022-07-11,Pitched,2025-03-10
14,000729f8-339a-426e-9811-d4a9b8243a09,"[{'uprn': 100100141540, 'buildingid': '000729f...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,29.0,0.0,0.0,86.8,86.8,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
15,00072bea-81a2-4659-b65c-65ed89997cbd,"[{'uprn': 10010059425, 'buildingid': '00072bea...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,28.5,11.3,0.0,83.9,95.2,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10
16,00073fae-bf0e-49ea-b7e4-be35adc7e474,"[{'uprn': 100100166752, 'buildingid': '00073fa...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,0.0,0.0,0.0,11.5,11.5,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10
17,0007425b-b4aa-41c6-b8af-db7669f97ed0,"[{'uprn': 100100714305, 'buildingid': '0007425...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,15.8,0.0,47.2,63.0,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
18,00074353-e088-4821-8967-60e1cc71f9d5,"[{'uprn': 100100671540, 'buildingid': '0007435...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,34.8,0.0,0.0,109.5,109.5,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
19,0007456c-3740-407e-ac88-2e20e2806db0,"[{'uprn': 100100020241, 'buildingid': '0007456...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2022-07-17,Not Present,...,12.6,0.0,0.0,91.3,91.3,Automated Process,Expected Data Output,2022-07-17,Pitched,2025-03-10
20,00074ca3-04b2-478b-a149-bc6558c3a1a3,"[{'uprn': 10033340641, 'buildingid': '00074ca3...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2022-07-11,Not Present,...,0.0,0.0,0.0,146.4,146.4,Automated Process,Expected Data Output,2022-07-11,Pitched,2025-03-10
21,00074e05-742f-4e9c-964c-85cba6a6206a,"[{'uprn': 10090842797, 'buildingid': '00074e05...",W92000004,Residential Accommodation,Multiple Residential Accommodation,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,0.0,0.0,54.7,54.7,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
22,0007537d-7614-4eb0-8ef9-81edaf507179,"[{'uprn': 100100401744, 'buildingid': '0007537...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2024-05-19,Not Present,...,13.4,0.0,0.0,61.5,61.5,Automated Process,Expected Data Output,2024-05-19,Pitched,2025-03-10
23,00f051b9-e0be-447c-aa0d-17f537a876f7,"[{'uprn': 64115569, 'buildingid': '00f051b9-e0...",W92000004,Residential Accommodation,Semi-Detached House,2025-05-16,Default Value,New Building Surveyed After Imagery Capture,NaN,Unknown,...,NaN,NaN,NaN,NaN,NaN,Default Value,New Building Surveyed After Imagery Capture,NaN,Unknown,2025-04-12
24,00075cbd-b342-41d8-8794-848128f3321c,"[{'uprn': 100070013487, 'buildingid': '00075cb...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2022-06-23,Not Present,...,0.0,0.0,0.0,72.9,72.9,Automated Process,Expected Data Output,2022-06-23,Pitched,2025-03-10
25,00077c06-ceb8-45c1-8f7c-1106d3afaec9,"[{'uprn': 100100594471, 'buildingid': '00077c0...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,0.0,0.0,57.7,57.7,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
26,00077eee-1f84-44bd-b128-b7edc022805e,"[{'uprn': 100100366520, 'buildingid': '00077ee...",W92000004,Residential Accommodation,Mid-Terrace House,2025-03-11,Automated Process,Expected Data Output,2024-05-19,Not Present,...,0.0,23.7,0.0,50.0,73.7,Automated Process,Expected Data Output,2024-05-19,Pitched,2025-03-10
27,00077f9b-e465-4315-8783-4388d22763e7,"[{'uprn': 200003763856, 'buildingid': '00077f9...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,0.0,0.0,103.3,103.3,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
28,0007a435-ba51-43f1-bc72-790786a55ba8,"[{'uprn': 100100393576, 'buildingid': '0007a43...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2024-05-19,Not Present,...,0.0,21.2,0.0,48.1,69.3,Automated Process,Expected Data Output,2024-05-19,Pitched,2025-03-10
29,000cd4e7-8487-4ca3-b40f-0fe6fcbd3beb,"[{'uprn': 100100410852, 'buildingid': '000cd4e...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-27,Not Present,...,27.8,0.0,0.0,63.7,63.7,Automated Process,Expected Data Output,2023-05-27,Pitched,2025-03-10

In [22]:
df['roofshapeaspect_shape'].value_counts()

roofshapeaspect_shape
Pitched    1294427
Flat         30393
Mixed        23259
Unknown      13523
Name: count, dtype: int64

In [5]:
# take a small sample - preferably including a row with a missing UPRN
sample = df.iloc[[1, 5, 10, 21, 31, 40], :]

sample.to_csv('os-ngd-sample.csv')

In [6]:
df.query("roofmaterial_primarymaterial == 'Waterproof Membrane Or Concrete'")

,osid,uprnreference,region,buildinguse,description,versiondate,roofmaterial_capturemethod,roofmaterial_confidenceindicator,roofmaterial_evidencedate,roofmaterial_greenroofpresence,...,roofshapeaspect_areafacingwest_m2,roofshapeaspect_areaflat_m2,roofshapeaspect_areaindeterminable_m2,roofshapeaspect_areapitched_m2,roofshapeaspect_areatotal_m2,roofshapeaspect_capturemethod,roofshapeaspect_confidenceindicator,roofshapeaspect_evidencedate,roofshapeaspect_shape,roofshapeaspect_updatedate
40,0007ccdb-aa65-4c39-b044-294ae0689a4f,"[{'uprn': 100100262355, 'buildingid': '0007ccd...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2022-07-11,Not Present,...,0.0,25.7,0.0,61.2,86.9,Automated Process,Expected Data Output,2022-07-11,Pitched,2025-03-10
49,00082fa5-1a7b-43fb-a27c-9b4026e16221,"[{'uprn': 200003176633, 'buildingid': '00082fa...",W92000004,Residential Accommodation,Semi-Detached House,2025-05-09,Automated Process,Expected Data Output,2022-06-23,Not Present,...,0.0,136.6,0.0,13.4,150.0,Automated Process,Expected Data Output,2022-06-23,Flat,2025-04-12
107,000af128-27df-4a2b-9026-9297817f72ac,[],W92000004,Residential Accommodation,Residential Building,2025-03-11,Automated Process,Insufficient Building Size,2023-05-20,Not Present,...,4.8,11.1,0.0,4.8,15.9,Automated Process,Insufficient Building Size,2023-05-20,Flat,2025-03-10
123,000bc146-d7b3-41bb-846a-b8f4457c0b63,"[{'uprn': 43017568, 'buildingid': '000bc146-d7...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2023-05-20,Not Present,...,0.0,0.0,0.0,70.7,70.7,Automated Process,Expected Data Output,2023-05-20,Pitched,2025-03-10
141,02ed0da2-b751-4ced-a376-ef12b5301f68,[],W92000004,Residential Accommodation,Residential Building,2025-03-11,Automated Process,Insufficient Building Size,2023-05-20,Not Present,...,0.0,9.9,0.0,0.0,9.9,Automated Process,Insufficient Building Size,2023-05-20,Flat,2025-03-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1361763,00034c09-6856-4bb2-b427-037fd8a4f9e8,"[{'uprn': 100100221437, 'buildingid': '00034c0...",W92000004,Residential Accommodation,Semi-Detached House,2025-03-11,Automated Process,Expected Data Output,2022-06-16,Not Present,...,0.0,59.9,0.0,21.2,81.1,Automated Process,Expected Data Output,2022-06-16,Flat,2025-03-10
1361778,02b41a07-0b2f-4f52-b2da-1610af9137e0,[],W92000004,Residential Accommodation,Residential Building,2025-03-11,Automated Process,Insufficient Building Size,2022-06-23,Not Present,...,0.0,0.0,0.0,13.0,13.0,Automated Process,Insufficient Building Size,2022-06-23,Pitched,2025-03-10
1361782,0003f105-63c8-4039-8423-ee15f1394c56,"[{'uprn': 10011744032, 'buildingid': '0003f105...",W92000004,Residential Accommodation,Detached House,2025-03-11,Automated Process,Expected Data Output,2022-06-23,Not Present,...,0.0,0.0,0.0,125.1,125.1,Automated Process,Expected Data Output,2022-06-23,Pitched,2025-03-10
1361810,000522f9-e48d-4987-869d-00ded971f07c,[],W92000004,Residential Accommodation,Residential Building,2025-03-11,Automated Process,Expected Data Output,2022-07-17,Not Present,...,0.0,19.6,0.0,0.0,19.6,Automated Process,Expected Data Output,2022-07-17,Flat,2025-03-10
1361827,00e8f652-deee-4d0a-8366-2da1644f81df,[],W92000004,Residential Accommodation,Residential Building,2025-03-11,Automated Process,Insufficient Building Size,2024-05-09,Not Present,...,0.0,14.7,0.0,0.0,14.7,Automated Process,Insufficient Building Size,2024-05-09,Flat,2025-03-10